create table if not exists HIT
(
    HIT_ID        INTEGER generated by default as identity not null,
    APP       VARCHAR not null,
    URI       VARCHAR not null,
    IP        VARCHAR not null,
    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE not null,
    constraint HIT_PK
        primary key (HIT_ID)
);

insert into HIT (app, uri, ip, timestamp)
values ( 'ewm-main-service', '/events/1', '192.163.0.1', '2022-09-06 11:00:23' );