create table if not exists HIT
(
    HIT_ID        INTEGER generated by default as identity not null,
    APP       VARCHAR not null,
    URI       VARCHAR not null,
    IP        VARCHAR not null,
    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE not null,
    constraint HIT_PK
        primary key (HIT_ID)
);
