create table if not exists HIT
(
    HIT_ID    BIGINT generated by default as identity not null,
    APP       VARCHAR(50) not null,
    URI       VARCHAR(50) not null,
    IP        VARCHAR(50) not null,
    TIMESTAMP TIMESTAMP WITHOUT TIME ZONE not null,
    constraint HIT_PK
        primary key (HIT_ID)
);
